apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - namespace.yaml
  - cloudflare-ddns/ks.yaml
  - cloudflare-tunnel/ks.yaml
  - netbird/ks.yaml
  - pod-gateway/ks.yaml
  - traefik/ks.yaml
  - unifi/ks.yaml
  - whoami/ks.yaml
