[tools]
kubectl = "latest"
task = "latest"
yq = "latest"
jq = "latest"

# Testing tools
flux2 = "latest"
kubeconform = "latest"
yamllint = "latest"
"npm:markdownlint-cli" = "latest"
"npm:prettier" = "latest"
"pipx:flux-local" = "8.1.0"
node = "latest"
pipx = "latest"
python = "3.14.3"
