---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vector-charts
  namespace: flux-system
spec:
  interval: 15m
  ref:
    tag: "0.50.0"
  url: https://helm.vector.dev
