apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-charts.yaml
  - bananaspliff-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - cilium-charts.yaml
  - cloudnative-pg-charts.yaml
  - deliveryhero-charts.yaml
  - descheduler-charts.yaml
  - emberstack-charts.yaml
  - external-dns-charts.yaml
  - external-secrets-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - intel-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - kasten-charts.yaml
  - kube-fledged-charts.yaml
  - kubereboot-kured-charts.yaml
  - kyverno-charts.yaml
  - lwolf-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - minio-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - pihole-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - spegel-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - vaultwarden-charts.yaml
  - vector-charts.yaml
  - wrmilling-charts.yaml
