# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - namespace.yaml
  - dragonfly/ks.yaml
  - minio/ks.yaml
  - obsidian-couchdb/ks.yaml
  - postgres/ks.yaml
