# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./descheduler/ks.yaml
  - ./external-dns/ks.yaml
  - ./external-secrets/ks.yaml
  - ./k8s-dns-gateway/ks.yaml
  - ./kube-cleanup-operator/ks.yaml
  - ./kyverno/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reflector/ks.yaml
  - ./reloader/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./spegel/ks.yaml
