apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - kube-system
  - cert-manager
  - flux-system
  - node-system
  - security
  - storage
  - ../../apps/system/external-secrets/ks.yaml
