apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - middlewares
  - dashboard
  - monitoring/service-monitor.yaml
  - monitoring/prometheusrules.yaml

namespace: networking
configMapGenerator:
  - name: traefik-dashboard
    files:
      - traefik-dashboard.json=https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana_folder: "System"
  labels:
    grafana_dashboard: "1"
