apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - adventurelog/ks.yaml
  - karakeep/ks.yaml
  - home-assistant/ks.yaml
  # - firefly-iii/ks.yaml
  - immich/ks.yaml
  - libreddit/ks.yaml
  - mealie/ks.yaml
  - n8n/ks.yaml
  # - nocodb/ks.yaml
  - outline/ks.yaml
  - paperless/ks.yaml
  # - penpot/ks.yaml
  - vikunja/ks.yaml
