apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - namespace.yaml
  # - nfs-provisioner-helm-release.yaml
  - rook-ceph/ks.yaml
  # - snapshot-controller.yaml
