apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.yaml
  - backups.yaml
  - cert-manager.yaml
  - databases.yaml
  - development.yaml
  - household.yaml
  - kube-system.yaml
  - media.yaml
  - monitoring.yaml
  - networking.yaml
  - node-system.yaml
  - other.yaml
  - storage.yaml
  - system.yaml
  - vaultwarden.yaml
